FROM debian:stretch-slim as builder

RUN apt-get update -q
RUN apt-get install -yq \
  autoconf \
  automake \
  libtool \
  make \
  gcc \
  git \
  autotools-dev \
  pkg-config \
  libc6-dev

WORKDIR /src
RUN git clone https://github.com/mininet/openflow
COPY util/openflow-patches/ openflow-patches/
WORKDIR /src/openflow
RUN patch -p1 < ../openflow-patches/controller.patch

RUN ./boot.sh && ./configure && make install

FROM scratch

COPY --from=builder /usr/local/bin/ /usr/local/bin/
